dataset:
  name: bank_loan
  train_path: s3://gretel-datasets/ml_ops/bank_loan/train.csv
  validation_path: null
  test_path: null
  target_column: Loan Status
  drop_columns: ID
ML:
  ml_task: classification
  objective: binary:logistic
  objective_type: Maximize
  ml_eval_metric: aucpr
  ml_metric_threshold: 0.0
gretel:
  strategy: balance
  generate_factor: 1.0
  target_balance: 1.0
  mode: cloud
  sink_bucket: null
