dataset:
  name: company-bankruptcy
  train_path: s3://gretel-datasets/ml_ops/company_bankruptcy/train.csv
  validation_path: null
  test_path: null
  target_column: Bankrupt?
  drop_columns: null
ML:
  ml_task: classification
  objective: binary:logistic
  objective_type: Maximize
  ml_eval_metric: aucpr
  ml_metric_threshold: 0.0
gretel:
  strategy: balance
  generate_factor: 1.0
  target_balance: 1.0
  mode: cloud
  sink_bucket: null
